import js from "@eslint/js";
import globals from "globals";
import tseslint from "typescript-eslint";

/**
 * Backend lint config for `@auric/core` (Core + the Mizan backend + scripts).
 * `mizan/web/` has its own flat config. Syntactic only — no type-aware rules,
 * to keep `npm run lint` fast and match the web setup.
 */
export default tseslint.config(
  {
    ignores: [
      "dist/**",
      "node_modules/**",
      "coverage/**",
      "storage/**",
      "core/kernel/db/schema.ts", // generated by prisma-kysely
      "mizan/web/**",
      "web/**",
      "**/*.js",
    ],
  },
  {
    files: ["**/*.ts"],
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: { ...globals.node },
    },
    rules: {
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
      // NOT `consistent-type-imports`: with `emitDecoratorMetadata`, a class
      // that appears only in a constructor-parameter type position is still a
      // runtime value (SWC reads it for `design:paramtypes`). The rule can't
      // see that and would break Nest DI. The codebase splits type/value
      // imports by hand — see docs/conventions.md.
      "@typescript-eslint/no-explicit-any": "warn",
      "@typescript-eslint/no-non-null-assertion": "off",
      "no-console": ["error", { allow: ["warn", "error"] }],
    },
  },
  {
    // CLI scripts, seeds and tests legitimately print to stdout.
    files: [
      "scripts/**/*.ts",
      "**/*.test.ts",
      "core/tests/**/*.ts",
      "**/tests/**/*.ts",
      "**/seed*.ts",
      "**/*seed*.ts",
    ],
    rules: { "no-console": "off" },
  },
);
