/**
 * The Mizan demo dataset, ported from
 * `mizan/web/src/mocks/fixtures/db.ts`. Dates are day-offsets from "now" and
 * resolved against the injected clock by the seeder. Local ids (`usr_dev`,
 * `cli_1`, …) are placeholders the seeder maps to real generated ids.
 */

export const DEMO_TEAM = [
  {
    key: "usr_dev",
    name: "Amira Tawfik",
    title: "Managing Partner",
    role: "firm_admin",
    email: "amira.tawfik@tawfikpartners.eg",
    phone: "+20 2 2735 1200",
    practiceAreas: ["Corporate", "Arbitration"],
    status: "active",
    weeklyCapacityHours: 40,
    bar: "Cairo Bar · 2001",
  },
  {
    key: "usr_2",
    name: "Karim Fahmy",
    title: "Partner",
    role: "partner",
    email: "karim.fahmy@tawfikpartners.eg",
    phone: "+20 2 2735 1201",
    practiceAreas: ["Litigation", "Employment"],
    status: "active",
    weeklyCapacityHours: 40,
    bar: "Cairo Bar · 2004",
  },
  {
    key: "usr_3",
    name: "Nour El-Sayed",
    title: "Senior Associate",
    role: "lawyer",
    email: "nour.elsayed@tawfikpartners.eg",
    phone: null,
    practiceAreas: ["Real Estate", "Corporate"],
    status: "active",
    weeklyCapacityHours: 40,
    bar: "Cairo Bar · 2012",
  },
  {
    key: "usr_4",
    name: "Omar Mansour",
    title: "Associate",
    role: "lawyer",
    email: "omar.mansour@tawfikpartners.eg",
    phone: null,
    practiceAreas: ["Litigation", "Tax"],
    status: "active",
    weeklyCapacityHours: 40,
    bar: "Cairo Bar · 2016",
  },
  {
    key: "usr_5",
    name: "Salma Adel",
    title: "Paralegal",
    role: "paralegal",
    email: "salma.adel@tawfikpartners.eg",
    phone: null,
    practiceAreas: ["Litigation"],
    status: "active",
    weeklyCapacityHours: 35,
    bar: null,
  },
  {
    key: "usr_6",
    name: "Hana Ibrahim",
    title: "Finance Manager",
    role: "finance",
    email: "hana.ibrahim@tawfikpartners.eg",
    phone: "+20 2 2735 1210",
    practiceAreas: [],
    status: "active",
    weeklyCapacityHours: 40,
    bar: null,
  },
  {
    key: "usr_7",
    name: "Youssef Halim",
    title: "Associate",
    role: "lawyer",
    email: "youssef.halim@tawfikpartners.eg",
    phone: null,
    practiceAreas: ["Arbitration", "Corporate"],
    status: "inactive",
    weeklyCapacityHours: 40,
    bar: "Cairo Bar · 2015",
  },
] as const;

export const DEMO_CLIENTS = [
  {
    key: "cli_1",
    name: "Al-Nour Trading Co.",
    type: "company",
    status: "active",
    email: "legal@alnour.com.eg",
    phone: "+20 2 2480 5500",
    taxId: "204-889-113",
    address: "12 El-Batal Ahmed Abdel Aziz St, Mohandessin, Giza",
    notes: "Long-standing retainer client. Prefers weekly updates.",
    createdDays: -540,
  },
  {
    key: "cli_2",
    name: "Delta Bank S.A.E.",
    type: "company",
    status: "active",
    email: "gc@deltabank.eg",
    phone: "+20 2 3336 7000",
    taxId: "200-114-778",
    address: "National Tower, Corniche El Nil, Cairo",
    notes: null,
    createdDays: -420,
  },
  {
    key: "cli_3",
    name: "Horizon Developments",
    type: "company",
    status: "active",
    email: "contracts@horizondev.eg",
    phone: "+20 2 2519 9042",
    taxId: "512-330-901",
    address: "New Cairo, First Settlement, Cairo",
    notes: "Real-estate portfolio; several concurrent matters.",
    createdDays: -300,
  },
  {
    key: "cli_4",
    name: "Mariam Zaki",
    type: "individual",
    status: "active",
    email: "mariam.zaki@gmail.com",
    phone: "+20 100 224 8890",
    taxId: null,
    address: "8 Road 9, Maadi, Cairo",
    notes: null,
    createdDays: -210,
  },
  {
    key: "cli_5",
    name: "Bright Foods Manufacturing",
    type: "company",
    status: "active",
    email: "admin@brightfoods.eg",
    phone: "+20 3 4270 1180",
    taxId: "331-556-220",
    address: "Borg El Arab Industrial Zone, Alexandria",
    notes: null,
    createdDays: -160,
  },
  {
    key: "cli_6",
    name: "Gulf Petro Logistics FZE",
    type: "company",
    status: "active",
    email: "legal@gulfpetro.ae",
    phone: "+971 4 883 2200",
    taxId: "AE-100-4471",
    address: "Jebel Ali Free Zone, Dubai, UAE",
    notes: "Cross-border; invoices in AED.",
    createdDays: -120,
  },
  {
    key: "cli_7",
    name: "Cedar Holdings",
    type: "company",
    status: "archived",
    email: null,
    phone: null,
    taxId: "119-002-654",
    address: "Downtown, Cairo",
    notes: "Engagement concluded 2025.",
    createdDays: -900,
  },
] as const;

export const DEMO_CONTACTS = [
  {
    clientKey: "cli_1",
    name: "Tarek Selim",
    role: "General Counsel",
    email: "t.selim@alnour.com.eg",
    phone: "+20 2 2480 5511",
    primary: true,
  },
  {
    clientKey: "cli_1",
    name: "Rania Gamal",
    role: "CFO",
    email: "r.gamal@alnour.com.eg",
    phone: null,
    primary: false,
  },
  {
    clientKey: "cli_2",
    name: "Hossam Farid",
    role: "Head of Legal",
    email: "h.farid@deltabank.eg",
    phone: "+20 2 3336 7042",
    primary: true,
  },
  {
    clientKey: "cli_3",
    name: "Dina Wagdy",
    role: "Development Director",
    email: "d.wagdy@horizondev.eg",
    phone: null,
    primary: true,
  },
  {
    clientKey: "cli_6",
    name: "Michael Ross",
    role: "Regional Legal Manager",
    email: "m.ross@gulfpetro.ae",
    phone: "+971 4 883 2214",
    primary: true,
  },
] as const;

export const DEMO_MATTERS = [
  {
    key: "mat_1",
    reference: "TP-2024-0111",
    title: "Al-Nour Trading v. Delta Bank — facility dispute",
    clientKey: "cli_1",
    practiceArea: "Litigation",
    status: "open",
    court: "Cairo Economic Court",
    leadKey: "usr_2",
    openedDays: -190,
    closedDays: null,
    description:
      "Dispute over acceleration of a EGP 40m credit facility and enforcement of security.",
  },
  {
    key: "mat_2",
    reference: "TP-2024-0140",
    title: "Horizon Developments — New Cairo land acquisition",
    clientKey: "cli_3",
    practiceArea: "Real Estate",
    status: "open",
    court: null,
    leadKey: "usr_3",
    openedDays: -150,
    closedDays: null,
    description: "Acquisition and title due diligence for a 22,000 sqm plot.",
  },
  {
    key: "mat_3",
    reference: "TP-2025-0007",
    title: "Bright Foods — distribution agreement review",
    clientKey: "cli_5",
    practiceArea: "Corporate",
    status: "open",
    court: null,
    leadKey: "usr_3",
    openedDays: -95,
    closedDays: null,
    description: "Review and negotiation of a regional distribution agreement.",
  },
  {
    key: "mat_4",
    reference: "TP-2025-0018",
    title: "Mariam Zaki — unfair dismissal claim",
    clientKey: "cli_4",
    practiceArea: "Employment",
    status: "open",
    court: "South Cairo Primary Court",
    leadKey: "usr_2",
    openedDays: -80,
    closedDays: null,
    description: "Claim for arbitrary dismissal and unpaid end-of-service benefits.",
  },
  {
    key: "mat_5",
    reference: "TP-2025-0026",
    title: "Gulf Petro — ICC arbitration (logistics contract)",
    clientKey: "cli_6",
    practiceArea: "Arbitration",
    status: "open",
    court: null,
    leadKey: "usr_dev",
    openedDays: -70,
    closedDays: null,
    description: "ICC arbitration seated in Cairo over a terminated logistics services contract.",
  },
  {
    key: "mat_6",
    reference: "TP-2025-0031",
    title: "Al-Nour Trading — tax assessment appeal",
    clientKey: "cli_1",
    practiceArea: "Tax",
    status: "open",
    court: "Cairo Court of Appeal",
    leadKey: "usr_4",
    openedDays: -60,
    closedDays: null,
    description: "Appeal against a corporate income tax reassessment for FY2023.",
  },
  {
    key: "mat_7",
    reference: "TP-2025-0044",
    title: "Horizon Developments — construction contract dispute",
    clientKey: "cli_3",
    practiceArea: "Litigation",
    status: "on_hold",
    court: "Giza Primary Court",
    leadKey: "usr_2",
    openedDays: -45,
    closedDays: null,
    description: "Contractor claim for delay damages; on hold pending settlement talks.",
  },
  {
    key: "mat_8",
    reference: "TP-2025-0051",
    title: "Delta Bank — regulatory advisory (consumer lending)",
    clientKey: "cli_2",
    practiceArea: "Corporate",
    status: "open",
    court: null,
    leadKey: "usr_dev",
    openedDays: -30,
    closedDays: null,
    description: "Advisory on new central bank consumer-lending rules.",
  },
  {
    key: "mat_9",
    reference: "TP-2025-0055",
    title: "Bright Foods — trademark opposition",
    clientKey: "cli_5",
    practiceArea: "Corporate",
    status: "open",
    court: null,
    leadKey: "usr_4",
    openedDays: -18,
    closedDays: null,
    description: "Opposition to a confusingly similar trademark application.",
  },
  {
    key: "mat_10",
    reference: "TP-2024-0090",
    title: "Cedar Holdings — shareholder exit",
    clientKey: "cli_7",
    practiceArea: "Corporate",
    status: "closed",
    court: null,
    leadKey: "usr_dev",
    openedDays: -800,
    closedDays: -360,
    description: "Negotiated buy-out of a minority shareholder.",
  },
] as const;

export const DEMO_PARTICIPANTS = [
  { matterKey: "mat_1", userKey: "usr_2", role: "Lead" },
  { matterKey: "mat_1", userKey: "usr_5", role: "Paralegal" },
  { matterKey: "mat_1", userKey: "usr_4", role: "Support" },
  { matterKey: "mat_5", userKey: "usr_dev", role: "Lead" },
  { matterKey: "mat_5", userKey: "usr_7", role: "Support" },
  { matterKey: "mat_2", userKey: "usr_3", role: "Lead" },
] as const;

export const DEMO_NOTES = [
  {
    matterKey: "mat_1",
    authorKey: "usr_2",
    body: "Client wants to avoid a public judgment — keep settlement channel open.",
    days: -30,
  },
  {
    matterKey: "mat_4",
    authorKey: "usr_2",
    body: "Key issue: whether the warning letters meet the procedural threshold under the Labour Law.",
    days: -15,
  },
] as const;

export const DEMO_UPDATES = [
  {
    matterKey: "mat_1",
    authorKey: "usr_2",
    body: "Filed the statement of defence. Next hearing set for the merits.",
    days: -20,
    documentNames: ["Statement of Defence — Al-Nour.pdf"],
  },
  {
    matterKey: "mat_1",
    authorKey: "usr_5",
    body: "Bundle of exhibits compiled and served on opposing counsel.",
    days: -9,
    documentNames: [],
  },
  {
    matterKey: "mat_5",
    authorKey: "usr_dev",
    body: "Terms of reference agreed with the tribunal. Procedural timetable circulated.",
    days: -12,
    documentNames: ["Terms of Reference — ICC.pdf"],
  },
] as const;

export const DEMO_HEARINGS = [
  {
    matterKey: "mat_1",
    court: "Cairo Economic Court",
    days: 2,
    hour: 9,
    status: "scheduled",
    purpose: "Merits hearing",
    outcome: null,
  },
  {
    matterKey: "mat_4",
    court: "South Cairo Primary Court",
    days: 5,
    hour: 11,
    status: "scheduled",
    purpose: "First session",
    outcome: null,
  },
  {
    matterKey: "mat_6",
    court: "Cairo Court of Appeal",
    days: 9,
    hour: 10,
    status: "scheduled",
    purpose: "Expert report review",
    outcome: null,
  },
  {
    matterKey: "mat_7",
    court: "Giza Primary Court",
    days: 16,
    hour: 9,
    status: "scheduled",
    purpose: "Case management",
    outcome: null,
  },
  {
    matterKey: "mat_1",
    court: "Cairo Economic Court",
    days: -14,
    hour: 9,
    status: "adjourned",
    purpose: "Merits hearing",
    outcome: "Adjourned at the court's motion for document review.",
  },
  {
    matterKey: "mat_4",
    court: "South Cairo Primary Court",
    days: -25,
    hour: 11,
    status: "decided",
    purpose: "Interim relief application",
    outcome: "Application for wage continuation granted.",
  },
] as const;

export const DEMO_TASKS = [
  {
    title: "Draft settlement memo for Al-Nour",
    matterKey: "mat_1",
    assigneeKey: "usr_dev",
    status: "in_progress",
    priority: "high",
    days: 1,
    createdDays: -4,
    completedDays: null,
  },
  {
    title: "Prepare hearing bundle — Mariam Zaki first session",
    matterKey: "mat_4",
    assigneeKey: "usr_5",
    status: "todo",
    priority: "high",
    days: 3,
    createdDays: -3,
    completedDays: null,
  },
  {
    title: "Review distribution agreement redlines",
    matterKey: "mat_3",
    assigneeKey: "usr_3",
    status: "todo",
    priority: "normal",
    days: 4,
    createdDays: -6,
    completedDays: null,
  },
  {
    title: "File trademark opposition grounds",
    matterKey: "mat_9",
    assigneeKey: "usr_4",
    status: "todo",
    priority: "normal",
    days: -1,
    createdDays: -8,
    completedDays: null,
  },
  {
    title: "Collect title deeds from client — New Cairo plot",
    matterKey: "mat_2",
    assigneeKey: "usr_dev",
    status: "todo",
    priority: "normal",
    days: -2,
    createdDays: -10,
    completedDays: null,
  },
  {
    title: "Circulate arbitration procedural timetable",
    matterKey: "mat_5",
    assigneeKey: "usr_dev",
    status: "done",
    priority: "normal",
    days: -12,
    createdDays: -14,
    completedDays: -12,
  },
  {
    title: "Respond to central bank consultation",
    matterKey: "mat_8",
    assigneeKey: "usr_dev",
    status: "todo",
    priority: "low",
    days: 12,
    createdDays: -5,
    completedDays: null,
  },
  {
    title: "Update client on tax appeal status",
    matterKey: "mat_6",
    assigneeKey: "usr_dev",
    status: "todo",
    priority: "normal",
    days: 2,
    createdDays: -2,
    completedDays: null,
  },
  {
    title: "Book process server for construction claim",
    matterKey: "mat_7",
    assigneeKey: "usr_5",
    status: "todo",
    priority: "low",
    days: null,
    createdDays: -7,
    completedDays: null,
  },
] as const;

export const DEMO_DOCUMENTS = [
  {
    name: "Statement of Defence — Al-Nour.pdf",
    matterKey: "mat_1",
    category: "Pleading",
    status: "filed",
    size: 284_113,
    mime: "application/pdf",
    byKey: "usr_2",
    days: -20,
  },
  {
    name: "Credit Facility Agreement (2021).pdf",
    matterKey: "mat_1",
    category: "Evidence",
    status: "final",
    size: 1_204_882,
    mime: "application/pdf",
    byKey: "usr_5",
    days: -40,
  },
  {
    name: "Title Search Report — Plot 22.pdf",
    matterKey: "mat_2",
    category: "Report",
    status: "draft",
    size: 512_004,
    mime: "application/pdf",
    byKey: "usr_3",
    days: -6,
  },
  {
    name: "Distribution Agreement v3 (redline).docx",
    matterKey: "mat_3",
    category: "Contract",
    status: "draft",
    size: 96_770,
    mime: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    byKey: "usr_3",
    days: -3,
  },
  {
    name: "Dismissal Letter — M. Zaki.pdf",
    matterKey: "mat_4",
    category: "Evidence",
    status: "final",
    size: 61_233,
    mime: "application/pdf",
    byKey: "usr_2",
    days: -16,
  },
  {
    name: "Engagement Letter — Gulf Petro.pdf",
    matterKey: "mat_5",
    category: "Admin",
    status: "signed",
    size: 142_889,
    mime: "application/pdf",
    byKey: "usr_dev",
    days: -70,
  },
  {
    name: "Terms of Reference — ICC.pdf",
    matterKey: "mat_5",
    category: "Pleading",
    status: "final",
    size: 331_220,
    mime: "application/pdf",
    byKey: "usr_dev",
    days: -12,
  },
  {
    name: "Tax Reassessment Notice FY2023.pdf",
    matterKey: "mat_6",
    category: "Evidence",
    status: "final",
    size: 208_441,
    mime: "application/pdf",
    byKey: "usr_4",
    days: -58,
  },
  {
    name: "Board Resolution — Bright Foods.pdf",
    matterKey: "mat_9",
    category: "Corporate",
    status: "draft",
    size: 44_120,
    mime: "application/pdf",
    byKey: "usr_4",
    days: -2,
  },
  {
    name: "Opposing Counsel Correspondence (bundle).pdf",
    matterKey: "mat_1",
    category: "Correspondence",
    status: "final",
    size: 903_551,
    mime: "application/pdf",
    byKey: "usr_5",
    days: -9,
  },
] as const;

export const DEMO_INVOICES = [
  {
    key: "inv_1",
    number: "INV-2026-0128",
    clientKey: "cli_1",
    matterKey: "mat_1",
    status: "sent",
    currency: "EGP",
    issuedDays: -45,
    dueDays: -15,
    vatRate: 0.14,
    lines: [
      { kind: "fee", description: "Professional fees — Feb", amount: 220_000 },
      { kind: "disbursement", description: "Court filing fees", amount: 4_500 },
    ],
  },
  {
    key: "inv_2",
    number: "INV-2026-0134",
    clientKey: "cli_3",
    matterKey: "mat_2",
    status: "sent",
    currency: "EGP",
    issuedDays: -30,
    dueDays: 0,
    vatRate: 0.14,
    lines: [{ kind: "fee", description: "Due diligence — phase 1", amount: 180_000 }],
  },
  {
    key: "inv_3",
    number: "INV-2026-0140",
    clientKey: "cli_6",
    matterKey: "mat_5",
    status: "issued",
    currency: "AED",
    issuedDays: -10,
    dueDays: 20,
    vatRate: 0.05,
    lines: [
      { kind: "fee", description: "Arbitration — retainer draw", amount: 60_000 },
      { kind: "disbursement", description: "ICC registration fee", amount: 3_000 },
    ],
  },
  {
    key: "inv_4",
    number: "INV-2026-0141",
    clientKey: "cli_5",
    matterKey: "mat_3",
    status: "draft",
    currency: "EGP",
    issuedDays: null,
    dueDays: null,
    vatRate: 0.14,
    lines: [{ kind: "fee", description: "Contract review", amount: 45_000 }],
  },
  {
    key: "inv_5",
    number: "INV-2026-0142",
    clientKey: "cli_1",
    matterKey: "mat_6",
    status: "paid",
    currency: "EGP",
    issuedDays: -60,
    dueDays: -30,
    vatRate: 0.14,
    lines: [{ kind: "fee", description: "Tax appeal — preparation", amount: 150_000 }],
  },
  {
    key: "inv_6",
    number: "INV-2026-0119",
    clientKey: "cli_2",
    matterKey: "mat_8",
    status: "paid",
    currency: "EGP",
    issuedDays: -80,
    dueDays: -50,
    vatRate: 0.14,
    lines: [{ kind: "fee", description: "Regulatory advisory", amount: 95_000 }],
  },
  {
    key: "inv_7",
    number: "INV-2026-0092",
    clientKey: "cli_2",
    matterKey: "mat_8",
    status: "paid",
    currency: "EGP",
    issuedDays: -150,
    dueDays: -120,
    vatRate: 0.14,
    lines: [{ kind: "fee", description: "Regulatory advisory — Q1 retainer", amount: 130_000 }],
  },
  {
    key: "inv_8",
    number: "INV-2026-0104",
    clientKey: "cli_3",
    matterKey: "mat_2",
    status: "sent",
    currency: "EGP",
    issuedDays: -108,
    dueDays: -78,
    vatRate: 0.14,
    lines: [
      { kind: "fee", description: "Due diligence — scoping", amount: 90_000 },
      { kind: "disbursement", description: "Company registry extracts", amount: 2_000 },
    ],
  },
  {
    key: "inv_9",
    number: "INV-2026-0146",
    clientKey: "cli_1",
    matterKey: "mat_1",
    status: "sent",
    currency: "EGP",
    issuedDays: -3,
    dueDays: 27,
    vatRate: 0.14,
    lines: [{ kind: "fee", description: "Professional fees — merits hearing", amount: 210_000 }],
  },
] as const;

export const DEMO_PAYMENTS = [
  {
    invoiceKey: "inv_5",
    amount: 171_000,
    currency: "EGP",
    method: "bank_transfer",
    days: -28,
    reference: "TRF-99120",
  },
  {
    invoiceKey: "inv_6",
    amount: 108_300,
    currency: "EGP",
    method: "bank_transfer",
    days: -47,
    reference: "TRF-98004",
  },
  {
    invoiceKey: "inv_1",
    amount: 100_000,
    currency: "EGP",
    method: "cheque",
    days: -8,
    reference: "CHQ-4471",
  },
  {
    invoiceKey: "inv_7",
    amount: 148_200,
    currency: "EGP",
    method: "bank_transfer",
    days: -150,
    reference: "TRF-96110",
  },
  {
    invoiceKey: "inv_8",
    amount: 60_000,
    currency: "EGP",
    method: "bank_transfer",
    days: -100,
    reference: "TRF-97330",
  },
  {
    invoiceKey: "inv_2",
    amount: 90_000,
    currency: "EGP",
    method: "bank_transfer",
    days: -92,
    reference: "TRF-97540",
  },
  {
    invoiceKey: "inv_9",
    amount: 120_000,
    currency: "EGP",
    method: "cheque",
    days: -1,
    reference: "CHQ-4488",
  },
] as const;

export const DEMO_EXPENSES = [
  {
    matterKey: "mat_1",
    description: "Court filing fees — merits hearing",
    category: "Court fees",
    amount: 3_200,
    currency: "EGP",
    status: "approved",
    days: -18,
    byKey: "usr_5",
  },
  {
    matterKey: "mat_5",
    description: "Expert witness retainer",
    category: "Experts",
    amount: 25_000,
    currency: "AED",
    status: "pending",
    days: -6,
    byKey: "usr_dev",
  },
  {
    matterKey: "mat_2",
    description: "Land registry search fees",
    category: "Disbursement",
    amount: 1_450,
    currency: "EGP",
    status: "approved",
    days: -9,
    byKey: "usr_3",
  },
  {
    matterKey: "mat_4",
    description: "Process server",
    category: "Disbursement",
    amount: 900,
    currency: "EGP",
    status: "pending",
    days: -2,
    byKey: "usr_5",
  },
  {
    matterKey: null,
    description: "Legal research subscription — quarterly",
    category: "Subscriptions",
    amount: 6_800,
    currency: "EGP",
    status: "approved",
    days: -20,
    byKey: "usr_6",
  },
] as const;

export const DEMO_EVENTS = [
  {
    title: "Client call — Al-Nour settlement strategy",
    kind: "meeting",
    startDays: 1,
    startHour: 14,
    endHour: 15,
    matterKey: "mat_1",
    ownerKey: "usr_2",
  },
  {
    title: "Internal review — arbitration timetable",
    kind: "meeting",
    startDays: 3,
    startHour: 12,
    endHour: 13,
    matterKey: "mat_5",
    ownerKey: "usr_dev",
  },
  {
    title: "Deadline: file opposition grounds",
    kind: "court_filing",
    startDays: -1,
    startHour: 17,
    endHour: null,
    matterKey: "mat_9",
    ownerKey: "usr_4",
  },
  {
    title: "Deadline: submit expert report",
    kind: "reminder",
    startDays: 7,
    startHour: 17,
    endHour: null,
    matterKey: "mat_6",
    ownerKey: "usr_4",
  },
] as const;

/** In-app notifications for the demo admin (Amira / usr_dev). Core `notifications`. */
export const DEMO_NOTIFICATIONS = [
  {
    type: "hearing.scheduled",
    title: "Hearing scheduled — Al-Nour Trading v. Delta Bank",
    body: "Cairo Economic Court, in 2 days at 09:00",
    matterKey: "mat_1",
    hoursAgo: 1,
    read: false,
  },
  {
    type: "task.assigned",
    title: "Task assigned — Draft settlement memo for Al-Nour",
    body: "Due tomorrow",
    matterKey: "mat_1",
    hoursAgo: 8,
    read: false,
  },
  {
    type: "invoice.paid",
    title: "Payment received — INV-2026-0142",
    body: "EGP 171,000",
    matterKey: null,
    hoursAgo: 26,
    read: false,
  },
  {
    type: "matter.update_added",
    title: "Update posted — Gulf Petro ICC arbitration",
    body: "Terms of reference agreed with the tribunal.",
    matterKey: "mat_5",
    hoursAgo: 50,
    read: true,
  },
] as const;

export const DEMO_ACTIVITY = [
  {
    actorKey: "usr_2",
    action: "matter.update_added",
    targetType: "matter",
    targetKey: "mat_1",
    label: "Al-Nour Trading v. Delta Bank",
    days: -9,
  },
  {
    actorKey: "usr_5",
    action: "document.uploaded",
    targetType: "document",
    targetKey: null,
    label: "Opposing Counsel Correspondence (bundle).pdf",
    days: -9,
  },
  {
    actorKey: "usr_dev",
    action: "hearing.scheduled",
    targetType: "hearing",
    targetKey: null,
    label: "Merits hearing — Al-Nour",
    days: -11,
  },
  {
    actorKey: "usr_6",
    action: "payment.recorded",
    targetType: "payment",
    targetKey: null,
    label: "EGP 100,000 against INV-2026-0128",
    days: -8,
  },
  {
    actorKey: "usr_3",
    action: "matter.opened",
    targetType: "matter",
    targetKey: "mat_9",
    label: "Bright Foods — trademark opposition",
    days: -18,
  },
  {
    actorKey: "usr_4",
    action: "task.completed",
    targetType: "task",
    targetKey: null,
    label: "Circulate arbitration procedural timetable",
    days: -12,
  },
] as const;
