import type { Copy } from "./copy-types";

export const EN: Copy = {
  brand: "Raqib",
  brandSub: "رقيب · by AURIC",
  menu: "Menu",
  nav: ["Platform", "How it works", "Product", "Capabilities", "Who it’s for", "Contact"],
  tryDemo: "Try the demo",
  signIn: "Sign in",
  explore: "Explore the platform",
  eyebrow: "FIELD OPERATIONS & INSPECTION MANAGEMENT",
  h1: "Complete visibility over every field inspection.",
  heroSub:
    "Raqib helps security and guarding companies standardize inspections, document field evidence, and connect review and management oversight in one workflow.",
  heroMeta: "One web application for desktop, tablet and phone · Arabic and English",
  m: {
    inProgress: "In progress",
    site: "Tower B · Main gate · Morning shift",
    section: "Section 2 of 5 · Access control · 11 of 17 items",
    score: "Running score",
    item: "Visitor ID verified against the register",
    weight: "Weight 3",
    c: "Compliant",
    nc: "Non-compliant",
    na: "N/A",
    note: "Two visitors entered without badge check at 07:40. Gate guard informed.",
    capture: "Take photo or video",
    after: "After submission",
    stages: ["Submitted", "Review", "Approval", "Approved"],
    caption:
      "Inspection screen as used on a phone. Non-compliant items require a note and evidence.",
  },
  probEyebrow: "THE OPERATIONAL PROBLEM",
  probTitle: "When field operations grow, consistency and visibility become harder to maintain.",
  probBody:
    "Each new site adds inspectors, shifts and reports. Without a shared process, management reviews results that were collected differently and stored in different places.",
  problems: [
    [
      "Inspections vary by site and team",
      "Each supervisor works from their own checklist, so scores can’t be compared.",
    ],
    [
      "Evidence is scattered",
      "Photos and notes stay on phones and in chat threads, separate from the finding they support.",
    ],
    ["Field execution is hard to see", "Missed or late visits surface after the fact, if at all."],
    [
      "Reporting is manual",
      "Monthly reports are assembled by hand from spreadsheets and messages.",
    ],
    ["Standards drift", "Checklists change without a record of what changed, when, or why."],
  ],
  howEyebrow: "HOW RAQIB WORKS",
  howTitle: "One workflow from the visit plan to the approved report.",
  steps: [
    [
      "Organize",
      "Quality schedules the visit, assigns the inspector, and the current form version is applied.",
    ],
    [
      "Inspect",
      "The inspector works through each section on a phone, answering weighted items as compliant, non-compliant or not applicable.",
    ],
    [
      "Document",
      "Non-compliant items require a note and evidence. Photos and video are captured in the browser and attached to the item.",
    ],
    [
      "Review",
      "A quality employee reviews the inspection and can return items for correction. Quality Management approves and the report is issued.",
    ],
  ],
  assigned: "Assigned",
  stepSample: ["Tower B · Main gate", "Sun 08:30 · Morning shift"],
  s3x: "2 files linked to item 2.3",
  s4a: "Forward for approval",
  s4b: "Return for completion",
  tourEyebrow: "THE PRODUCT",
  tourTitle: "The screens your teams will use.",
  tourNote: "Captured from the working Raqib application with fictional demo data.",
  tour: [
    [
      "inspect-tab",
      "Inspection",
      "phone",
      "The inspection, section by section, on a tablet or phone.",
      "Large answer buttons, a running score, and save-and-continue-later. Non-compliant items ask for a note and evidence before the inspector can move on.",
      "Inspector · tablet · phone",
      "raqib/visits/VIS-26-0418/inspect",
    ],
    [
      "review",
      "Review",
      "desk",
      "Every answer, note and file in one review screen.",
      "The reviewer flags items that need changes and returns, rejects or forwards the inspection. The form version used is stated at the top.",
      "Quality employee · desktop",
      "raqib/reviews/VIS-26-0409",
    ],
    [
      "form",
      "Form builder",
      "desk",
      "Forms edited as drafts, published as versions.",
      "Sections, weighted items and answer rules. The draft shows how many inspections are bound to it before it is published.",
      "Quality management · desktop",
      "raqib/forms/FRM-SEC-01",
    ],
    [
      "analytics",
      "Analytics",
      "desk",
      "Indicators that explain themselves.",
      "Compliance, visit execution, open observations and corrective actions by period. Each indicator opens its definition and the records behind it.",
      "Quality management · project managers",
      "raqib/analytics",
    ],
    [
      "report",
      "PDF report",
      "desk",
      "The report a client receives.",
      "Issued after approval, in Arabic or English, with visit details, every item and the decision history.",
      "Quality management · desktop",
      "raqib/reports/RPT-26-0398",
    ],
  ],
  capEyebrow: "CAPABILITIES",
  capTitle: "Built around how inspections are actually carried out.",
  aT: "Standard forms, with every change on record.",
  aD: "Forms are built from sections and weighted items. Editing a published form creates a new version, and each inspection stays linked to the version it was carried out on, so past reports never change.",
  aPoints: [
    "Required items, weights and N/A rules per item",
    "Draft, published and archived versions with change comparison",
    "Publishing a version requires a release note",
  ],
  aForm: "Security Site Inspection",
  aNewV: "Create new version",
  aLock: "approved inspections keep the version they were carried out on.",
  versions: [
    ["v2.2", "Radio test added; checkpoint weight raised to 3", "Not yet used", "Draft", "warning"],
    [
      "v2.1",
      "ID badges and incident register items added",
      "14 inspections",
      "Published",
      "success",
    ],
    ["v2.0", "Documentation section added", "203 inspections", "Archived", "neutral"],
    ["v1.4", "Initial approved release", "38 inspections", "Archived", "neutral"],
  ],
  bT: "Visits that are planned, assigned and accounted for.",
  bD: "Year, month, week and day views. Rescheduling or cancelling a visit requires a reason, and overdue visits are flagged.",
  visits: [
    ["04", "Oct", "Tower B · Main gate", "VIS-26-0418", "Morning", "In progress", "info"],
    [
      "04",
      "Oct",
      "Warehouse 3 · Loading bay",
      "VIS-26-0409",
      "Morning",
      "Pending review",
      "review",
    ],
    ["02", "Oct", "Car park · Gate 2", "VIS-26-0402", "Night", "Returned", "warning"],
    ["30", "Sep", "Perimeter · North fence", "VIS-26-0395", "Evening", "Overdue", "danger"],
  ],
  cT: "Evidence attached to the finding it supports.",
  cD: "Each photo, video or document belongs to a specific inspection item, observation or corrective action. Uploads show progress and can be retried, and video plays through a protected link.",
  cItem: "Emergency exit unobstructed",
  cMeta: "Uploaded by inspector · 07:52 · stored privately, no public links",
  evidence: [
    ["JPG", "IMG_0418.jpg", "Uploaded", "success"],
    ["MP4", "exit-walk.mp4", "Uploading 64%", "info"],
    ["JPG", "IMG_0419.jpg", "Failed · Retry", "danger"],
  ],
  dT: "Reports ready to send to management and clients.",
  dD: "Approved inspections produce a PDF in Arabic or English with the form version, every answer, evidence, corrective actions and signatures. Period reports and analytics are generated inside Raqib and export to Excel.",
  dDoc: "Inspection report",
  clientLogo: "CLIENT LOGO",
  reportKv: [
    ["Reference", "RPT-26-0402"],
    ["Form", "v2.1"],
    ["Score", "76%"],
    ["Site", "Gate 2"],
    ["Shift", "Night"],
    ["Status", "Approved"],
  ],
  reportRows: [
    ["1.1", "Guard post staffed per roster", "Compliant", "success"],
    ["1.2", "Patrol log signed every 2h", "Compliant", "success"],
    ["2.3", "Visitor ID verified", "Non-compl.", "danger"],
    ["3.1", "CCTV recording verified", "N/A", "neutral"],
  ],
  signs: [
    ["Inspector", "K. Al-Shehri"],
    ["Reviewer", "N. Al-Qahtani"],
    ["Approver", "S. Al-Otaibi"],
  ],
  eT: "Access defined by role and by project.",
  eD: "Role templates set what each person can do. Project scope sets where. Review and approval are separate permissions, and confidential reports are granted to named individuals only.",
  eRole: "Role",
  permCols: ["View", "Submit", "Review", "Approve"],
  permRows: [
    ["Quality Management", "1111"],
    ["Quality Employee", "1010"],
    ["Project Manager", "1000"],
    ["Inspector", "1100"],
  ],
  eNote:
    "An inspector can submit inspections only for visits assigned to them, inside their projects.",
  rolesEyebrow: "WHO IT’S FOR",
  rolesTitle: "The same process, seen from each role.",
  rolesBody:
    "Each person sees the part of the workflow they are responsible for, and nothing outside their projects.",
  roles: [
    [
      "Inspector",
      "Today’s visits, the inspection form, evidence capture, and any items returned for correction.",
      "Phone",
    ],
    [
      "Quality employee",
      "The review queue. Flags items, returns for completion, rejects, or forwards for approval.",
      "Desktop · tablet",
    ],
    [
      "Quality management",
      "Approvals, scheduling, form versions, users and permissions, and analytics across all projects.",
      "Desktop",
    ],
    [
      "Project manager",
      "Their own projects: results, repeated issues, and the corrective actions assigned to them.",
      "Desktop · phone",
    ],
    [
      "Guards supervisor",
      "Guard evaluations in their scope and training requests for specific employees.",
      "Phone · tablet",
    ],
  ],
  recEyebrow: "TRACEABILITY",
  recTitle: "Every inspection should leave a clear, usable record.",
  recBody:
    "A finding stays connected to its evidence, its decision history and the corrective action that closes it. Decisions record who made them, their role, the time and the reason.",
  chain: [
    {
      step: "Inspection",
      title: "Item 2.3 marked non-compliant",
      ref: "VIS-26-0409 · 2.3",
      lines: [
        ["Visitor ID not checked", "Weight 3", "danger"],
        ["Form version v2.1", "", "neutral"],
      ],
    },
    {
      step: "Finding and evidence",
      title: "Observation raised",
      ref: "OBS-26-0231",
      lines: [
        ["2 photos, 1 video", "", "success"],
        ["Repeated ×3 in 6 weeks", "", "warning"],
      ],
    },
    {
      step: "Inspection record",
      title: "Decision history",
      ref: "VIS-26-0409",
      lines: [
        ["Submitted · Inspector", "07:58", "info"],
        ["Returned · Quality employee", "10:15", "warning"],
        ["Approved · Quality Mgmt", "14:20", "success"],
      ],
    },
    {
      step: "Report",
      title: "Issued after approval",
      ref: "RPT-26-0409.pdf",
      lines: [
        ["Arabic and English", "", "neutral"],
        ["Linked to form v2.1", "", "neutral"],
      ],
    },
  ],
  caT: "Corrective action",
  caSub: "Closure requires quality review. Uploading evidence alone does not close an action.",
  caSteps: [
    "Raised from finding",
    "Assigned · due date",
    "In progress",
    "Evidence submitted",
    "Quality review",
    "Closed",
  ],
  langEyebrow: "ARABIC AND ENGLISH",
  langTitle: "Each language designed properly, not translated on top.",
  langBody:
    "Arabic is a complete right-to-left layout. Users choose their language, and the same records read correctly in both.",
  langPoints: [
    "Navigation, tables, forms and charts mirror for Arabic",
    "Gregorian dates and Western digits in both languages",
    "Reference codes and times always read left to right",
    "PDF reports issued in Arabic or English",
  ],
  ctaTitle: "Bring greater visibility to your field operations.",
  ctaBody:
    "See how Raqib can help your team standardize inspections, document findings, and improve operational oversight.",
  ctaMeta: "A walkthrough using a working demo with fictional projects and roles.",
  footDesc: "Security quality and field inspection management for guarding companies.",
  footNav: "Pages",
  byAuric: "Raqib is a product by AURIC.",
};
