import js from "@eslint/js";
import globals from "globals";
import tseslint from "typescript-eslint";

/**
 * Lint config for @atlas/backend. Mirrors the root repo's eslint.config.js
 * (same rules, same Node-focused ruleset) since this package is Atlas's own
 * fully separate backend deployment, not part of the root workspace.
 */
export default tseslint.config(
  {
    ignores: [
      "dist/**",
      "node_modules/**",
      "coverage/**",
      "storage/**",
      "app/realestate/db/schema.ts", // generated by prisma-kysely
      "**/*.js",
    ],
  },
  {
    files: ["**/*.ts"],
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: { ...globals.node },
    },
    rules: {
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
      "@typescript-eslint/no-explicit-any": "warn",
      "@typescript-eslint/no-non-null-assertion": "off",
      "no-console": ["error", { allow: ["warn", "error"] }],
    },
  },
  {
    files: ["scripts/**/*.ts", "**/*.test.ts", "**/tests/**/*.ts", "**/seed*.ts", "**/*seed*.ts"],
    rules: { "no-console": "off" },
  },
);
